version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: chatify-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db   # Use volume instead folder local

  backend:
    build:
      context: ./backend
    container_name: chatify-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:admin123@mongo:27017/chatify-app?authSource=admin"